### ISSUE TITLE
BrM Rotation Helper Errors

### ISSUE THREAD

**Issue by anchastain** [rnyberg/Redfella-s-WA-Custom-Functions#1]
```
[string "return function() aura_env.updateInterval =..."]:159: attempt to compare nil with number
[string "return function() aura_env.updateInterval =..."]:159: in function `ready'
[string "return -- UNIT_POWER_FREQUENT, SPELL_UPDATE..."]:202: in function `triggerFunc'
WeakAuras\GenericTrigger.lua:494: in function `ScanEvents'
WeakAuras\GenericTrigger.lua:834: in function <WeakAuras\GenericTrigger.lua:832>

Locals:
spell = "chi_wave"
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to compare nil with number"
```
I have run into this error spamming me endlessly any time I target a mob.

I had the same error with the previous version of the weakaura and had since removed it.  Noticed that you had updated the auras today and was hoping that might have resolved it, but no such luck.

**Comment by rnyberg** [comment]
This issue is related to https://github.com/WeakAuras/WeakAuras2/issues/94

I'm going to try to get a bandaid solution out while those guys figure it out.

**Comment by rnyberg** [comment]
Temporary fix in place, try the Rotation Helper @ https://wago.io/4JhTdTdDW
