### ISSUE TITLE
New Brewmaster 3.0 link

### ISSUE THREAD

**Issue by Montrazul** [rnyberg/Redfella-s-WA-Custom-Functions#11]
I guess something went wrong with your link on [google docs](https://docs.google.com/document/d/1EwNIq_jWJodPhqOxd1H6LGzk8lMGDk-MaSMCaGscYWE/edit#)

    https://wago.io/EkKYtRRJf

Is leading to a castbar which (i just guess) has nothing to do with your Brewmaster 3.0 changes.

**Comment by rnyberg** [comment]
The strings were set to private, my bad.
