### ISSUE TITLE
Brew problem

### ISSUE THREAD

**Issue by BiggieSmallsRIP** [rnyberg/Redfella-s-WA-Custom-Functions#12]
even if un-talented brew rotation helper tells you to use chi burst.

**Comment by Montrazul** [comment]
And also (I dont know if intended or not) the brewmaster cds are squished (40 width and 25 height)

**Comment by rnyberg** [comment]
The height/width is intended so they take up less screen estate, I can live with the stretched texture, but you can make them 40/40 if you wish.

I'll fix Chi Burst tomorrow.

**Comment by BiggieSmallsRIP** [comment]
any eta ?

**Comment by rnyberg** [comment]
Tomorrow probably, latest on Sunday.
