### ISSUE TITLE
DK Textures wrong size and position

### ISSUE THREAD

**Issue by Montrazul** [rnyberg/Redfella-s-WA-Custom-Functions#13]
3 of the 6 textures (shield, vampir and bloodlust) have the wrong size and position

**Comment by rnyberg** [comment]
Screenshot please.

What resolution are you playing on?

**Comment by rnyberg** [comment]
http://i.imgur.com/xhxbEdZ.png

Your Model Displays seem to have wrong options checked for some reason.

**Comment by Montrazul** [comment]
Yes you are right. Somehow when I import the WA strings the checkmark is set. If I put it out the sizes and positions are correct.
