### ISSUE TITLE
xct+ update

### ISSUE THREAD

**Issue by Roxall** [rnyberg/Redfella-s-WA-Custom-Functions#15]
Your saved variables download from: https://docs.google.com/document/d/1EwNIq_jWJodPhqOxd1H6LGzk8lMGDk-MaSMCaGscYWE/edit#
Seems to be broken when it comes to xCT+.
Whenever I use the command /reflux switch redfella, xCT+ tells me that I'm forced to completely reset my profile and there's no way around it. Could you possible update that saved variable file to avoid this?

**Comment by rnyberg** [comment]
Ah, XCT+ recently updated and decided that everyone needs to wipe out their XCT+ settings. I don't see much point in sharing my profile as I only have incoming heals visible nowadays with pretty much default settings.
