### ISSUE TITLE
Veng DH Rotation helper

### ISSUE THREAD

**Issue by gleedy** [rnyberg/Redfella-s-WA-Custom-Functions#16]
Maybe it's my fault..but the rotation helper is constantly telling me to use Felblade, even when it's on cooldown.

**Comment by gleedy** [comment]
To add more..it does show other things in what seems like the right times, it just adds fel blade in when it's on cooldown, fairly often

**Comment by lattenwald** [comment]
Same for me. First I hacked in specific check in aura_env.ready function, but then found this comment on another wago.io rotation page:

> Posted by alcaras 2 days ago. Reply 2017-01-18 18:38
> Updated Felblade's spell ID to 232893 and that fixed the issues I was seeing.

Re-imported, did this and it works now. It's in VDH Rotation Helper aura, under Actions->Custom action on init.

**Comment by rnyberg** [comment]
Yeah, spell ID issue indeed. Closing this issue and pushing out an update tomorrow.

**Comment by gleedy** [comment]
Thank you all for the help
