### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by jfdhuiz** [rnyberg/Redfella-s-WA-Custom-Functions#3]
1) https://wago.io/NkpfXwrnW this WA can be added to your aura bars, it will mention quest progress because sometimes the PvP quest gets hidden in quest log. Its a port from Spinalcrack's version to your style.
2) Ring dynamic fury: max fury / 10 = increment (not correct LUA tho I did saw correct LUA for this in a WA somewhere). In my case I got an extra 2x 10 fury from gem, so its 12 (not the best gem and will replace, but the talent will be used eventually as well). Start with 1. At end it goes from 109 till 120. I just copied yours and made one with max 120 for Havoc. On Vengeance I got max 100 pain so I just use your default with enabled Vengeance only.
3) I saw you had the artifact disabled in the HDL and enabled that. I'm also not sure Fel Barrage is being prioritized enough (although it got nerfed as well). Finally, I find it annoying how Meta is sometimes suggested when I don't want it (alt+shift+r would remove too much). I just want to have an option to remove Meta from the CD though whereas skipping FotI is too much AoE DPS loss.
4) I also fixed your momentum WA: https://wago.io/41pakOBh-

**Comment by rnyberg** [comment]
Thanks for these, I'm currently finishing up BDK 2.0, and next on the line is trying to get Havoc out of beta. These will help a lot.

**Comment by rnyberg** [comment]
1) Imported your quest tracker. 2.1 @ https://wago.io/VJmAHIMwW

2) Modified Pain & Fury Circle to calculate segment size dynamically based on max power / 10, so that each segment represents 10% of your max power instead of flat 10 pain/fury. 2.1 @ https://wago.io/4kU4tHKiZ

3) Well that was a stupid mistake, I disabled it during LibArtifactData bug period and forgot it to false. Thanks for noticing. Fixed in 2.0.1 @ https://wago.io/NJjdRSKtW

4) Fixed in 2.0.1 @ https://wago.io/4yjdWUMvW

**Comment by jfdhuiz** [comment]
1 & 2) Thanks!

3) Thanks. What about the other statements?

4) Momentum is enabled for Vengeance, swapped it to Havoc. I also moved the glow a little bit down, and to the right. Same with the Meta glow from Havoc Rotation Helper, I moved it slightly to the right. Exports here: https://wago.io/VJhjUGL3Z Momentum changes WAs https://wago.io/N17MwMUhb

**Comment by rnyberg** [comment]
I'll tweak the positioning and change the load rule tomorrow, bit busy with other things now.

For the offensive suggestions, there's only one "optimal way" to use them, which is Nemesis into Meta into Chaos Blades, and then Nemesis into Chaosblades if Meta is on CD for longer than 2 minutes.

I don't want to add a third cooldown trigger there, so it's basicly all CDs or nothing for now -- once I move my APL's to Hekilis addon later on, anyone can easily toggle abilities on/off change the rules when they are suggested.

**Comment by jfdhuiz** [comment]
Sure, no rush.

For Momentum texture, -13, -72 is ideal.

Have you considered something like Kib's Prepared for fury regen prediction?

Shadowmeld CD is Vengeance only; should be not specific. Could also add Arcane Torrent for belf.

Finally, with all your settings imported I got some bleeding with icons on top and left

**Comment by rnyberg** [comment]
What do you mean by bleeding? Screenshot would be nice! 

I'll add belf racial and untick Shadowmeld spec rule. 

I had my own version of predictive pain in earlier versions, but to be honest, I didn't find it that useful in demanding content, while it was fancy and sweet to look at during boring grinding.

**Comment by jfdhuiz** [comment]
Sure, shot here: https://imgur.com/a/sbyp9
Look very close at the left and the top. Its more obvious with some abilities than others, but its quite obvious here.

Thanks for fixing Shadowmeld. I made various modifications. Won't share the Shadowmeld one.

Auras added:
Metamorphosis (Vengeance): https://wago.io/N1Z7Gb_3- (fixed)
Metamorphosis (Havoc): https://wago.io/EkQUMW_3Z (added)
Shard of Rokmora: https://wago.io/NkH2kZOhZ
Parjesh's Medallion: https://wago.io/4JJlx-u2b
Withered Scenario: https://wago.io/NkX8xZd3b (shows progress bar based on avg health and shows # of Withered alive)

CDs added:
Shard of Rokmora: https://wago.io/VyiFZ-_nb
Parjesh's Medallion: https://wago.io/N1T3WZ_3Z
Last Resort: https://wago.io/V1R0bZd2b

Didn't add anything to CDP lists.

Prepared added to Fury circle: https://wago.io/N1Djg-_nb
Prepared added to Tank HUD Resource TXT : https://wago.io/41pAxZdnW
Includes mods to resource txt check for Prepared buff, and check if Prepared is selected.

**Comment by rnyberg** [comment]
This is quite extensive and I appreciate your effort a lot, sadly my timetable for the coming days is very tight, but I'll try to evaluate, test and incorporate everything you shared asap!

**Comment by rnyberg** [comment]
Oh and still can't see what you mean by bleeding, I'll check the shot on my desktop, could be I just can't spot it on this shitty phone. :p

**Comment by jfdhuiz** [comment]
Cheers!

Here is the bleeding articulated: https://imgur.com/a/dCG8G zoom in those spots on original picture. Its like that with every WA, but it is more apparent on some than on others. I solved it with a quick hack (changed HDR's size to 45 by 45 and I don't notice it anymore).

PS: I'll be able to test the Withered WA again in 2 days. I made some slight mods to it after I finished the scenario. Also, I'm not yet happy with the Prepared WA behavior.

**Comment by rnyberg** [comment]
Ah, I believe this might be ElvUI Pixel Perfect clashing with Masque, or plain UI scaling affecting it. I've noticed similar bleeding with Progress Texture background colors showing up around the foreground.

**Comment by jfdhuiz** [comment]
Additions & fixes I made:

DH: Redfella's Auras 2.1:
Shard of Rokmora: https://wago.io/Ek89BIUTZ
Parjesh's Medallion: https://wago.io/VJ_0rIUT-
Jacin's Ruse: https://wago.io/Vk_ZI8U6W
Tirathon's Betrayal: https://wago.io/VyRFILITZ
Ravaged Seed Pod: https://wago.io/EJyCUILpb
Quest Tracker: https://wago.io/41I-wIL6-
Withered Scenario: https://wago.io/V1UXPILa-

DH: Redfella's Pain & Fury Circle 2.1 with Prepared support (updated, with only calculating logic once): https://wago.io/EyXWi8UaZ

DH: Redfella's Priority Cooldowns 2.0:
CD: Old War: https://wago.io/N1rnj8Lab (Havoc only)
CD: Health pot: https://wago.io/VyEWnI86W (fix for Legion health pots)
CD: Tirathon's Betrayal: https://wago.io/VyuL3UL6b
CD: Ravaged Seed Pod: https://wago.io/EJFtnI8Tb

DH: Redfella's Secondary Cooldowns 2.0:
CD: Shadowmeld: https://wago.io/VkrdTLI6Z
CD: Shard of Rokmora: https://wago.io/NkwiaLI6Z
CD: Parjesh's Medallion: https://wago.io/VkCTTILab
CD: Last Resort: https://wago.io/EJ3eCLIaZ (in the export I forgot to set this to Demon Hunter + Vengeance load only)
CD: Jacin's Ruse: https://wago.io/V1L8R8LTW
CD: Tirathon's Betrayal: https://wago.io/N1Y5R8ITW

DH: Redfella's Cooldown Pulse 2.0:
Nothing added yet. Should do I suppose?

DH: Redfella's Havoc Rotation 2.0.1:
Consume Magic H 3: https://wago.io/Nk5lVDUp- (this is for focus interrupt for Havoc only, should add one for Vengeance)

I added the versions because I haven't been able to import your latest changes because we're out of sync and its a bitch to resync.

**Comment by rnyberg** [comment]
I imported all of the Auras and CDs I were missing (However I put some in secondary that you had in primary), so they'll be included in the next update.

I won't be adding predictive pain & fury for my version, so you can have it public on wago if you want to.

**Comment by jfdhuiz** [comment]
Thanks a lot! I don't quite understand why and what you put in primary or secondary, maybe you could explain? Will probably feed you more updates as I progress through M+ fishing for trinkets.

**Comment by rnyberg** [comment]
For example in my current version I've moved potions out of primary to secondary, since having combat & health pot state "USED" in the primary area was adding unnecessary clutter in the important area of my screen.

**Comment by jfdhuiz** [comment]
Makes sense thanks for the explanation.

I made one more, Cenarius trinket: https://wago.io/VkOI4m5aW

Still waiting to get Ursoc's trinket.

**Comment by jfdhuiz** [comment]
Finally got Ursoc's trinket.

Here's the WA:
https://wago.io/NJcWvJFRb
