### ISSUE TITLE
Redfellas WA Rot Helper

### ISSUE THREAD

**Issue by Loopbr** [rnyberg/Redfella-s-WA-Custom-Functions#4]
Hey man I've been using your rotation helper for quite a while, and would like to thank you for your work  but I keep having some issues the rotation helper sometimes it has a HUGE downtime, for instance, let's say I make a pull and use D&D and marrowrend so now I have 2 stacks of bone shield and and 3 runes open. rotation goes on to tell me to BB, I do, it tells me to BB again, I do, now i have <2 stacks of BS and >3 runes rotation helper just stop and tell me to wait blood boil CD. I'm using 2.3v Def cd Disabled and Off CD Disabled. Is it suposed to be that way?

Talents and gear: http://us.battle.net/wow/en/character/azralon/Loopquatro/advanced

**Comment by Loopbr** [comment]
Here I made a video, https://www.youtube.com/watch?v=yA83S-as378&feature=youtu.be

It used to be just like on your demo video, IDK why one day it just became like this, I cannot make it work for the life of me, all it does it marrowrend-bb-bb-marrowrend-repeat.... ty

**Comment by rnyberg** [comment]
Found the problem and fixed it, will push an update out tomorrow probably. If you want to verify that I fixed it properly, here's a pastebin link that includes only the blood rotation helper display: http://pastebin.com/aN05kvR1

**Comment by Loopbr** [comment]
Hey man it somewhat worked I sometimes have a few more spells on rotation. Thank you for your work anyway.

**Comment by rnyberg** [comment]
What I fixed was Death Strike not being recommended due defensive CD switch being off, even when RP is capped. I'll do another pass tomorrow to see if I had a similar conditional error with another ability.

What's your talent setup btw?

**Comment by Loopbr** [comment]
Heartbreaker
Rapid Decomposition
Anti-Magic Barrier
Red Thirst
Tremble Before Me
Foul Bulwark
Purgatory

**Comment by rnyberg** [comment]
I think the problem is that you are running Anti-Magic Barrier, My strings might still be expecting you to run RD+Ossuary since it's been the most optimal talent setup since early beta.

**Comment by Loopbr** [comment]
Humn seems to be working now. Thank you vm!
