### ISSUE TITLE
Monk: WA not circular

### ISSUE THREAD

**Issue by Montrazul** [rnyberg/Redfella-s-WA-Custom-Functions#5]
Hello,

in your demonstration video for the monk I saw that your Weakauras are circular. 
When I disable Addonskins in ElvUI for WeakAuras and install Masque and Masque: Trinity
the weakauras of the brewmaster arent skinned at all. they are still rectangular.

**Comment by Montrazul** [comment]
Same with your new DH and DK WeakAuras. They all arent getting styled by Masque.

**Comment by rnyberg** [comment]
This is from the document:

HOW TO SETUP HEX-SHAPED ICONS

Open the Masque in-game menu by typing /masque
Choose a skin from the dropdown called "Adorn: Light Hex"
Optional: Darken the main color (Default) so the bezel of the icon isn’t very white
If your icons appear very dark with a square border behind the them, make sure you uncheck WeakAuras from ElvUI addonskins options.

For v1.0 I had round icons, for 2.0 hex shaped, but same applies.

**Comment by Montrazul** [comment]
Yes. But there is no "Adorn: Light Hex" and i also did not ask for the hex form :) I asked for the circular. Like it is at your brewmaster weakauras.

**Comment by Montrazul** [comment]
I read all your instructions and i did all of what was written there. But when i write /masque there is no dropdown anywhere where there is "Adorn: Light Hex"

**Comment by rnyberg** [comment]
Did you download both of the Masque addons I listed?
